//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamDataForum.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamDataForum.Resources.ModelsRes", typeof(ModelsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country name cannot be more than 100 symbols..
        /// </summary>
        public static string ErrorCountryNameMaxLength {
            get {
                return ResourceManager.GetString("ErrorCountryNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country name is required..
        /// </summary>
        public static string ErrorCountryNameRequired {
            get {
                return ResourceManager.GetString("ErrorCountryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date for forum is required..
        /// </summary>
        public static string ErrorForumDateRequired {
            get {
                return ResourceManager.GetString("ErrorForumDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum description cannot be more than 300 symbols..
        /// </summary>
        public static string ErrorForumDescriptionMaxLength {
            get {
                return ResourceManager.GetString("ErrorForumDescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum description is required..
        /// </summary>
        public static string ErrorForumDescriptionRequired {
            get {
                return ResourceManager.GetString("ErrorForumDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum title cannot be more than 300 symbols..
        /// </summary>
        public static string ErrorForumTitleMaxLength {
            get {
                return ResourceManager.GetString("ErrorForumTitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum title is required..
        /// </summary>
        public static string ErrorForumTitleRequired {
            get {
                return ResourceManager.GetString("ErrorForumTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post text is required..
        /// </summary>
        public static string ErrorPostTextTextRequired {
            get {
                return ResourceManager.GetString("ErrorPostTextTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread date is required..
        /// </summary>
        public static string ErrorThreadDateRequired {
            get {
                return ResourceManager.GetString("ErrorThreadDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread title cannot be more than 300 symbols..
        /// </summary>
        public static string ErrorThreadTitleMaxLength {
            get {
                return ResourceManager.GetString("ErrorThreadTitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread title is required..
        /// </summary>
        public static string ErrorThreadTitleRequired {
            get {
                return ResourceManager.GetString("ErrorThreadTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town name cannot be more than 100 symbols..
        /// </summary>
        public static string ErrorTownNameMaxLength {
            get {
                return ResourceManager.GetString("ErrorTownNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town name is required..
        /// </summary>
        public static string ErrorTownNameRequired {
            get {
                return ResourceManager.GetString("ErrorTownNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required..
        /// </summary>
        public static string ErrorUserFirstnameRequired {
            get {
                return ResourceManager.GetString("ErrorUserFirstnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image path cannot be more than 500 sumbols..
        /// </summary>
        public static string ErrorUserImagePathLength {
            get {
                return ResourceManager.GetString("ErrorUserImagePathLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required..
        /// </summary>
        public static string ErrorUserLastnameRequired {
            get {
                return ResourceManager.GetString("ErrorUserLastnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be more than 50 symbols..
        /// </summary>
        public static string ErrorUserNameMaxLength {
            get {
                return ResourceManager.GetString("ErrorUserNameMaxLength", resourceCulture);
            }
        }
    }
}
