//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamDataForum.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamDataForum.Resources.ModelsRes", typeof(ModelsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country name cannot be more than 100 symbols..
        /// </summary>
        public static string ErrorCountryNameMaxLength {
            get {
                return ResourceManager.GetString("ErrorCountryNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country name is required..
        /// </summary>
        public static string ErrorCountryNameRequired {
            get {
                return ResourceManager.GetString("ErrorCountryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date for forum is required..
        /// </summary>
        public static string ErrorForumDateRequired {
            get {
                return ResourceManager.GetString("ErrorForumDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum description cannot be more than 300 symbols..
        /// </summary>
        public static string ErrorForumDescriptionMaxLength {
            get {
                return ResourceManager.GetString("ErrorForumDescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum description is required..
        /// </summary>
        public static string ErrorForumDescriptionRequired {
            get {
                return ResourceManager.GetString("ErrorForumDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum title cannot be more than 300 symbols..
        /// </summary>
        public static string ErrorForumTitleMaxLength {
            get {
                return ResourceManager.GetString("ErrorForumTitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum title is required..
        /// </summary>
        public static string ErrorForumTitleRequired {
            get {
                return ResourceManager.GetString("ErrorForumTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid moderator..
        /// </summary>
        public static string ErrorModeratorIdRequired {
            get {
                return ResourceManager.GetString("ErrorModeratorIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum is not found..
        /// </summary>
        public static string ErrorNoForum {
            get {
                return ResourceManager.GetString("ErrorNoForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one moderator..
        /// </summary>
        public static string ErrorNoModerators {
            get {
                return ResourceManager.GetString("ErrorNoModerators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread is not found..
        /// </summary>
        public static string ErrorNoThread {
            get {
                return ResourceManager.GetString("ErrorNoThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post text cannot be more than 2000 symbols..
        /// </summary>
        public static string ErrorPostTextMaxValue {
            get {
                return ResourceManager.GetString("ErrorPostTextMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post text cannot be less than 10 symbols..
        /// </summary>
        public static string ErrorPostTextMinValue {
            get {
                return ResourceManager.GetString("ErrorPostTextMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post text is required..
        /// </summary>
        public static string ErrorPostTextTextRequired {
            get {
                return ResourceManager.GetString("ErrorPostTextTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no selected moderators ..
        /// </summary>
        public static string ErrorRequiredModerators {
            get {
                return ResourceManager.GetString("ErrorRequiredModerators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread date is required..
        /// </summary>
        public static string ErrorThreadDateRequired {
            get {
                return ResourceManager.GetString("ErrorThreadDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No forum is specified for this thread..
        /// </summary>
        public static string ErrorThreadNoForum {
            get {
                return ResourceManager.GetString("ErrorThreadNoForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No post is specified for this thread..
        /// </summary>
        public static string ErrorThreadNoPost {
            get {
                return ResourceManager.GetString("ErrorThreadNoPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread title cannot be more than 300 symbols..
        /// </summary>
        public static string ErrorThreadTitleMaxLength {
            get {
                return ResourceManager.GetString("ErrorThreadTitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread title cannot be less than 5 symbols..
        /// </summary>
        public static string ErrorThreadTitleMinLength {
            get {
                return ResourceManager.GetString("ErrorThreadTitleMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread title is required..
        /// </summary>
        public static string ErrorThreadTitleRequired {
            get {
                return ResourceManager.GetString("ErrorThreadTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town name cannot be more than 100 symbols..
        /// </summary>
        public static string ErrorTownNameMaxLength {
            get {
                return ResourceManager.GetString("ErrorTownNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town name is required..
        /// </summary>
        public static string ErrorTownNameRequired {
            get {
                return ResourceManager.GetString("ErrorTownNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password does not match password..
        /// </summary>
        public static string ErrorUserConfirmPasswordMatch {
            get {
                return ResourceManager.GetString("ErrorUserConfirmPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password cannot be less than 6 symbols..
        /// </summary>
        public static string ErrorUserConfirmPasswordMinLength {
            get {
                return ResourceManager.GetString("ErrorUserConfirmPasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password is required..
        /// </summary>
        public static string ErrorUserConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ErrorUserConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password cannot be more than 50 symbols..
        /// </summary>
        public static string ErrorUserConfrimPasswordMaxLength {
            get {
                return ResourceManager.GetString("ErrorUserConfrimPasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be more than 50 symbols..
        /// </summary>
        public static string ErrorUserEmailMaxLength {
            get {
                return ResourceManager.GetString("ErrorUserEmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be less than 5 symbols..
        /// </summary>
        public static string ErrorUserEmailMinLength {
            get {
                return ResourceManager.GetString("ErrorUserEmailMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string ErrorUserEmailRequired {
            get {
                return ResourceManager.GetString("ErrorUserEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required..
        /// </summary>
        public static string ErrorUserFirstnameRequired {
            get {
                return ResourceManager.GetString("ErrorUserFirstnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image path cannot be more than 500 sumbols..
        /// </summary>
        public static string ErrorUserImagePathLength {
            get {
                return ResourceManager.GetString("ErrorUserImagePathLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required..
        /// </summary>
        public static string ErrorUserLastnameRequired {
            get {
                return ResourceManager.GetString("ErrorUserLastnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be more than 50 symbols..
        /// </summary>
        public static string ErrorUserNameMaxLength {
            get {
                return ResourceManager.GetString("ErrorUserNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be more than 50 sumbols..
        /// </summary>
        public static string ErrorUserPasswordMaxLength {
            get {
                return ResourceManager.GetString("ErrorUserPasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be less than 6 symbols..
        /// </summary>
        public static string ErrorUserPasswordMinLength {
            get {
                return ResourceManager.GetString("ErrorUserPasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string ErrorUserPasswordRequired {
            get {
                return ResourceManager.GetString("ErrorUserPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be more than 256 symbols..
        /// </summary>
        public static string ErrorUserUsernameMaxLength {
            get {
                return ResourceManager.GetString("ErrorUserUsernameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required..
        /// </summary>
        public static string ErrorUserUsernameRequired {
            get {
                return ResourceManager.GetString("ErrorUserUsernameRequired", resourceCulture);
            }
        }
    }
}
